// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xyeblzjuejqreiejnhgv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh5ZWJsemp1ZWpxcmVpZWpuaGd2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI1MzkwOTksImV4cCI6MjA2ODExNTA5OX0.1e2Z9lfRIp2Zbda0tCHYmapeK0Z65FLGLuYr05d-j1E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});